services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: ticket-box-api
    tty: true
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - ticket-box-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: ticket-box-worker
    tty: true
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - ticket-box-network

  database:
    image: postgres:15
    container_name: ticket-box-database
    volumes:
      - ticket-box-database-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      TZ: "UTC"
    networks:
      - ticket-box-network

  redis:
    image: redis/redis-stack:latest
    container_name: ticket-box-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ticket-box-redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    environment:
      REDIS_ARGS: "--requirepass redispass"
    networks:
      - ticket-box-network

volumes:
  ticket-box-database-data:
  ticket-box-redis-data:

networks:
  ticket-box-network:
    driver: bridge
